apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/sonja434/webshop-payment-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: paymentdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432