apiVersion: v1
kind: Secret
metadata:
  name: webshop-secrets
type: Opaque
stringData:
  db-username: postgres
  db-password: postgres123
  jwt-secret: 4c7e91f2a8b54d1e9f3c6a7b8d2e5f109a3b6c8d1e4f7a9b2c5d8e1f4a7b0c3
  mail-username: ssekulic239@gmail.com
  mail-password: tzpy vlji fyue udhd