server:
  port: 8086

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${MAIL_USERNAME:ssekulic239@gmail.com}
    password: ${MAIL_PASSWORD:tzpy vlji fyue udhd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true