# ============================================================
# INPUT - prikuplja logove iz Docker kontejnera
# ============================================================
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# ============================================================
# FILTER - parsira Spring Boot JSON logove
# ============================================================
<filter **>
  @type parser
  key_name log
  reserve_data true
  remove_key_name_field true
  <parse>
    @type json
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>
</filter>

# ============================================================
# OUTPUT - šalje logove u Elasticsearch
# ============================================================
<match **>
  @type elasticsearch
  host elasticsearch
  port 9200
  logstash_format true
  logstash_prefix webshop
  logstash_dateformat %Y.%m.%d
  include_tag_key true
  tag_key @log_name
  flush_interval 1s
  <buffer>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_interval 5s
    retry_forever false
    retry_max_interval 30
    chunk_limit_size 2M
    queue_limit_length 8
    overflow_action block
  </buffer>
</match>